# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build_Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      # Set up .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'
      # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
      # Build the app
    - name: Build
    # --no-restore - skip package update step
      run: dotnet build --no-restore
      
      # Run the tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      # --no-build - CLI will not compile the code before running the tests
      # --verbosity normal - this controls how much information you see in the terminal
